version: '3'
services:
  orders-db:
    container_name: orders-db
    image: postgres:14.1-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    networks:
      - orders-net

  mcs-orders:
    container_name: mcs-orders
    build: 
      context: ./Orders
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      CONNECTION_STRING: "postgresql://admin:admin@orders-db:5432/ordersdb"
    restart: always
    networks:
      - orders-net 
      - app-net
    depends_on:
      - orders-db

  notifications-db:
    container_name: notifications-db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: notificationsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    networks:
      - notifications-net
  
  mcs-notifications:
    container_name: mcs-notifications
    build: 
      context: ./Notifications
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      CONNECTION_STRING: "postgresql://admin:admin@notifications-db:5432/notificationsdb"
    restart: always
    networks:
      - notifications-net 
      - app-net
    depends_on:
      - notifications-db
  
  nginx:
    container_name: api-gateway
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./Nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-net
    depends_on:
      - mcs-notifications

networks:
  app-net:
    driver: bridge
  notifications-net:
    driver: bridge
  orders-net:
    driver: bridge